import type { InstrumentWorkspace } from '@/lib/api'

export const workspace: InstrumentWorkspace = {
  comparison: null,
  decision: {
    draft: {
      as_of: '2026-08-08T12:00:00Z',
      created_at: '2026-08-08T12:00:00Z',
      disposition: 'draft',
      evidence: {
        costs: { fee_bps: 1.5, half_spread_bps: null, slippage_bps: 2.5, spread_status: 'confirmation-quote-required' },
        forecast_artifact_id: null,
        forecast_blockers: ['No promoted artifact for this range.'],
        forecast_eligible: null,
        forecast_limitations: [],
        forecast_metrics: [],
        forecast_paths: [],
        forecast_synthetic: null,
        history_dataset_id: 'demo-history',
        history_dataset_revision: 1,
        history_duplicates: [],
        history_gaps: [],
        history_generated_at: '2026-08-08T12:00:00Z',
        history_limitations: ['Synthetic data'],
        history_source: 'demo-synthetic',
      },
      instrument: {
        currency: 'USD', instrument_type: 'equity', metadata: {}, symbol: 'NVDA', venue: 'moomoo',
      },
      market_state: {
        invalidation: 176,
        key_level_bar_times: ['2026-08-07T20:00:00Z'],
        latest_close: 184,
        observed_drawdown: -0.08,
        observed_volatility: 0.24,
        resistance: 195,
        sma20: 185,
        sma50: 180,
        support: 180,
        trend: 'bullish',
      },
      operator_reason: null,
      packet_id: 'packet-draft-000000000001',
      paper_capability: {
        allowed: false,
        blockers: [{ code: 'forecast-missing', evidence_ref: 'workspace', message: 'No promoted artifact for this range.' }],
      },
      parent_packet_id: null,
      proposal_id: null,
      risk_plan: {
        entry_price: 182,
        proposal_input_only: true,
        reward_per_unit: 18,
        reward_to_risk: 3,
        risk_per_unit: 6,
        stop_price: 176,
        suggested_notional: 1820,
        suggested_quantity: 10,
        target_price: 200,
      },
      scenarios: [
        { confidence: 'qualitative', confidence_reason: 'Not calibrated.', invalidation: 180, kind: 'bull', probability: null, target: 210, thesis: 'Bull thesis', trigger: 'Bull trigger' },
        { confidence: 'qualitative', confidence_reason: 'Not calibrated.', invalidation: 178, kind: 'base', probability: null, target: 200, thesis: 'Base thesis', trigger: 'Base trigger' },
        { confidence: 'qualitative', confidence_reason: 'Not calibrated.', invalidation: 176, kind: 'bear', probability: null, target: 165, thesis: 'Bear thesis', trigger: 'Bear trigger' },
      ],
      selected_range: '6m',
      version: 1,
    },
    latest: null,
  },
  forecast: null,
  forecast_unavailable_reason: 'No promoted artifact for this range.',
  generated_at: '2026-08-08T12:00:00Z',
  history: {
    adjustment: 'unadjusted',
    as_of: '2026-08-08T12:00:00Z',
    bars: [
      {
        adjusted_close: null,
        close: 184,
        high: 185,
        instrument: {
          currency: 'USD',
          instrument_type: 'equity',
          metadata: {},
          symbol: 'NVDA',
          venue: 'moomoo',
        },
        interval: '1d',
        is_live_tail: false,
        live_lineage: null,
        low: 180,
        open: 181,
        timestamp: '2026-08-07T20:00:00Z',
        volume: 1_200_000,
      },
    ],
    calendar: 'XNYS',
    coverage: {
      end: '2026-08-07T20:00:00Z',
      interval: '1d',
      rows: 1,
      start: '2026-08-07T20:00:00Z',
      symbol: 'NVDA',
      venue: 'moomoo',
    },
    coverage_scope: 'historical-only',
    dataset_id: 'demo-history',
    dataset_revision: 1,
    duplicates: [],
    gaps: [],
    generated_at: '2026-08-08T12:00:00Z',
    instrument: {
      currency: 'USD',
      instrument_type: 'equity',
      metadata: {},
      symbol: 'NVDA',
      venue: 'moomoo',
    },
    interval: '1d',
    license: 'demo-synthetic',
    limitations: ['Synthetic data'],
    range: '6m',
    resolution_fallback: null,
    source: 'demo-synthetic',
  },
  instrument: {
    currency: 'USD',
    instrument_type: 'equity',
    metadata: {},
    symbol: 'NVDA',
    venue: 'moomoo',
  },
  live: {
    age_ms: 95_000,
    ask: 184.2,
    bid: 183.8,
    data_time: '2026-08-08T11:58:25Z',
    label: 'stale',
    last: 184,
    provenance: 'demo-synthetic',
    reason: 'Quote age exceeds the paper-action fence.',
    received_at: '2026-08-08T11:58:25Z',
    sequence: 12,
    sequence_gap: false,
    source: 'demo-synthetic',
    status: 'degraded',
  },
  position: null,
  proposal: {
    allowed: false,
    blockers: ['Quote age exceeds the paper-action fence.'],
    proposals: [],
  },
  risk: {
    cash: 100_000,
    equity: 100_000,
    global_kill_switch: false,
    mark_available: true,
    valuation_complete: true,
    valuation_reason: null,
    max_notional: 50_000,
    max_order_quantity: 100,
    max_position_quantity: 1_000,
    starting_cash: 100_000,
    venue_kill_switch: false,
  },
}
