/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Summary */
        get: operations["account_summary_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Summary */
        get: operations["api_account_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["api_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enablement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enablement */
        get: operations["api_enablement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["api_experiments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecasts */
        get: operations["api_forecasts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{venue}/{symbol}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument History */
        get: operations["api_instrument_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{venue}/{symbol}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument Workspace */
        get: operations["api_instrument_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kill Switch */
        get: operations["api_kill_switch"];
        put?: never;
        /** Kill Switch Json */
        post: operations["api_kill_switch_json"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Prediction
         * @description The prediction comparison surface (Phase E): per pair, per
         *     venue the implied probability (mid), bid/ask, spread bps, touch
         *     depth, book liquidity and the feed's freshness label, plus the
         *     cross-venue probability difference — a pure fold of the feed's
         *     latest state at one explicit clock, so the labels and the
         *     numbers in one response always agree.
         */
        get: operations["api_live_prediction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/price-trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Price Trail */
        get: operations["api_live_price_trail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Replay
         * @description Replay a recorded window from the local lake in append
         *     (``local_seq``) order. ``start``/``end`` bound the window on
         *     ``received_at``; both must be timezone-aware ISO instants.
         *     Every returned update keeps its venue, provenance, event time,
         *     receive time, sequence and gap marks — the replay surface is the
         *     same evidence contract the live surface uses, labeled as
         *     replayed, never folded into the live cache.
         */
        get: operations["api_live_replay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/replay/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Replay Windows
         * @description The recorded replay extent (iteration 0019 slice 4): the
         *     earliest/latest ``received_at``, row count and venues of the
         *     attached replay lake. A feed without a lake, or a lake that
         *     holds nothing yet, answers 404 with an honest reason — there is
         *     no fabricated window.
         */
        get: operations["api_live_replay_windows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live State
         * @description The latest update per venue+instrument+kind, with the
         *     provenance+age label the watchlist badges on.
         */
        get: operations["api_live_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Status
         * @description Per-venue connector health from the supervisors' STATUS
         *     transitions (connected/lagging/stale/disconnected/unavailable).
         */
        get: operations["api_live_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Stream
         * @description SSE fallback: one ``data:`` event per normalized update,
         *     with a heartbeat comment every 15 s.
         */
        get: operations["api_live_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markets */
        get: operations["api_markets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders */
        get: operations["api_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order */
        get: operations["api_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["api_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Paper Proposal */
        post: operations["api_create_paper_proposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/proposals/{proposal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Paper Proposal */
        post: operations["api_confirm_paper_proposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pnl */
        get: operations["api_pnl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["api_positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Promotions */
        get: operations["api_promotions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk */
        get: operations["api_risk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist */
        get: operations["api_watchlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enablement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_enablement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{venue}/{symbol}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument History */
        get: operations["instrument_history_instruments__venue___symbol__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{venue}/{symbol}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument Workspace */
        get: operations["instrument_workspace_instruments__venue___symbol__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kill Switch */
        get: operations["kill_switch_kill_switch_get"];
        put?: never;
        /** Kill Switch Post */
        post: operations["kill_switch_post_kill_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_kill_switch_control_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Prediction
         * @description The prediction comparison surface (Phase E): per pair, per
         *     venue the implied probability (mid), bid/ask, spread bps, touch
         *     depth, book liquidity and the feed's freshness label, plus the
         *     cross-venue probability difference — a pure fold of the feed's
         *     latest state at one explicit clock, so the labels and the
         *     numbers in one response always agree.
         */
        get: operations["live_prediction_live_prediction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/price-trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Price Trail */
        get: operations["live_price_trail_live_price_trail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Replay
         * @description Replay a recorded window from the local lake in append
         *     (``local_seq``) order. ``start``/``end`` bound the window on
         *     ``received_at``; both must be timezone-aware ISO instants.
         *     Every returned update keeps its venue, provenance, event time,
         *     receive time, sequence and gap marks — the replay surface is the
         *     same evidence contract the live surface uses, labeled as
         *     replayed, never folded into the live cache.
         */
        get: operations["live_replay_live_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/replay/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Replay Windows
         * @description The recorded replay extent (iteration 0019 slice 4): the
         *     earliest/latest ``received_at``, row count and venues of the
         *     attached replay lake. A feed without a lake, or a lake that
         *     holds nothing yet, answers 404 with an honest reason — there is
         *     no fabricated window.
         */
        get: operations["live_replay_windows_live_replay_windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live State
         * @description The latest update per venue+instrument+kind, with the
         *     provenance+age label the watchlist badges on.
         */
        get: operations["live_state_live_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Status
         * @description Per-venue connector health from the supervisors' STATUS
         *     transitions (connected/lagging/stale/disconnected/unavailable).
         */
        get: operations["live_status_live_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Stream
         * @description SSE fallback: one ``data:`` event per normalized update,
         *     with a heartbeat comment every 15 s.
         */
        get: operations["live_stream_live_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders */
        get: operations["orders_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order */
        get: operations["order_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Paper Proposal */
        post: operations["create_paper_proposal_paper_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/proposals/{proposal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Paper Proposal */
        post: operations["confirm_paper_proposal_paper_proposals__proposal_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pnl */
        get: operations["pnl_pnl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_portfolio_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_portfolio_pnl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_promotions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect */
        get: operations["redirect_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Watchlist Add */
        post: operations["watchlist_add_watchlist_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Watchlist Remove */
        post: operations["watchlist_remove_watchlist_remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_kill_switch_post_kill_switch_post */
        Body_kill_switch_post_kill_switch_post: {
            /** Action */
            action?: string | null;
            /** Confirm */
            confirm?: string | null;
            /** Venue */
            venue?: string | null;
        };
        /** Body_watchlist_add_watchlist_add_post */
        Body_watchlist_add_watchlist_add_post: {
            /** Symbol */
            symbol: string;
        };
        /** Body_watchlist_remove_watchlist_remove_post */
        Body_watchlist_remove_watchlist_remove_post: {
            /** Symbol */
            symbol: string;
        };
        /**
         * ComparisonPoint
         * @description Normalized closes for one timestamp shared by every comparison series.
         */
        ComparisonPoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /**
         * ComparisonSeries
         * @description Close-price comparison over the exact shared observed timestamps.
         */
        ComparisonSeries: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Keys */
            keys: string[];
            /** Limitations */
            limitations?: string[];
            /** Points */
            points: components["schemas"]["ComparisonPoint"][];
            range: components["schemas"]["HistoryRange"];
        };
        /**
         * CoverageSnapshot
         * @description Detached, frozen UTC view of canonical manifest coverage.
         */
        CoverageSnapshot: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Interval */
            interval: string;
            /** Rows */
            rows: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Symbol */
            symbol: string;
            venue: components["schemas"]["Venue"];
        };
        /**
         * ForecastMetrics
         * @description Promotion evidence for one horizon.
         */
        ForecastMetrics: {
            /** Benchmark Mae */
            benchmark_mae: number;
            /** Coverage 50 */
            coverage_50: number;
            /** Coverage 80 */
            coverage_80: number;
            /** Coverage 95 */
            coverage_95: number;
            /** Interval Test Count */
            interval_test_count: number;
            /** Mae */
            mae: number;
            /** Residual Count */
            residual_count: number;
            /** Rmse */
            rmse: number;
            /**
             * Sessions
             * @enum {integer}
             */
            sessions: 7 | 30 | 126;
            /** Test End */
            test_end?: string | null;
            /** Test Start */
            test_start?: string | null;
            /** Validation End */
            validation_end?: string | null;
            /** Validation Start */
            validation_start?: string | null;
        };
        /**
         * ForecastPath
         * @description A complete price path for one predeclared horizon.
         */
        ForecastPath: {
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
            /**
             * Sessions
             * @enum {integer}
             */
            sessions: 7 | 30 | 126;
        };
        /**
         * ForecastPoint
         * @description One future session and its ordered price quantiles.
         */
        ForecastPoint: {
            /** P025 */
            p025: number;
            /** P10 */
            p10: number;
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
            /** P90 */
            p90: number;
            /** P975 */
            p975: number;
            /** Session */
            session: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoricalBar
         * @description One observed OHLCV bar returned by the history service.
         */
        HistoricalBar: {
            /** Adjusted Close */
            adjusted_close?: number | null;
            /** Close */
            close: number;
            /** High */
            high: number;
            instrument: components["schemas"]["InstrumentSnapshot"];
            /** Interval */
            interval: string;
            /**
             * Is Live Tail
             * @default false
             */
            is_live_tail: boolean;
            live_lineage?: components["schemas"]["LiveTailLineage"] | null;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Volume */
            volume: number;
        };
        /**
         * HistoricalPayload
         * @description Stable wire envelope for observed history and optional comparison.
         */
        HistoricalPayload: {
            comparison?: components["schemas"]["ComparisonSeries"] | null;
            primary: components["schemas"]["HistoricalSeries"];
        };
        /**
         * HistoricalSeries
         * @description Observed history and the exact manifest provenance used to read it.
         */
        HistoricalSeries: {
            /**
             * Adjustment
             * @enum {string}
             */
            adjustment: "unadjusted" | "split-adjusted" | "total-return";
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Bars */
            bars: components["schemas"]["HistoricalBar"][];
            /** Calendar */
            calendar: string;
            coverage: components["schemas"]["CoverageSnapshot"];
            /**
             * Coverage Scope
             * @default historical-only
             * @constant
             */
            coverage_scope: "historical-only";
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Revision */
            dataset_revision: number;
            /** Duplicates */
            duplicates?: string[];
            /** Gaps */
            gaps?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            instrument: components["schemas"]["InstrumentSnapshot"];
            /** Interval */
            interval: string;
            /** License */
            license: string;
            /** Limitations */
            limitations?: string[];
            range: components["schemas"]["HistoryRange"];
            /** Resolution Fallback */
            resolution_fallback?: string | null;
            /** Source */
            source: string;
        };
        /**
         * HistoryRange
         * @description Supported chart windows and their stable wire values.
         * @enum {string}
         */
        HistoryRange: "1d" | "5d" | "1m" | "3m" | "6m" | "1y";
        /** Instrument */
        Instrument: {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            instrument_type: components["schemas"]["InstrumentType"];
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
            /** Symbol */
            symbol: string;
            venue: components["schemas"]["Venue"];
        };
        /**
         * InstrumentSnapshot
         * @description Detached, deeply immutable view of the canonical Instrument schema.
         */
        InstrumentSnapshot: {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            instrument_type: components["schemas"]["InstrumentType"];
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
            /** Symbol */
            symbol: string;
            venue: components["schemas"]["Venue"];
        };
        /**
         * InstrumentType
         * @enum {string}
         */
        InstrumentType: "equity" | "etf" | "perpetual" | "spot" | "event_contract";
        /**
         * InstrumentWorkspace
         * @description Point-in-time read model for one venue-aware decision workspace.
         */
        InstrumentWorkspace: {
            comparison?: components["schemas"]["ComparisonSeries"] | null;
            forecast?: components["schemas"]["WorkspaceForecast"] | null;
            /** Forecast Unavailable Reason */
            forecast_unavailable_reason?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            history: components["schemas"]["HistoricalSeries"];
            instrument: components["schemas"]["InstrumentSnapshot"];
            live: components["schemas"]["WorkspaceLiveEvidence"];
            position?: components["schemas"]["WorkspacePosition"] | null;
            proposal: components["schemas"]["ProposalCapability"];
            risk: components["schemas"]["WorkspaceRisk"];
        };
        /**
         * LiveTailLineage
         * @description Positive, point-in-time evidence attached only to a live-tail bar.
         */
        LiveTailLineage: {
            /** Age Ms */
            age_ms: number;
            /**
             * Continuity Proven
             * @constant
             */
            continuity_proven: true;
            /**
             * Data Time
             * Format: date-time
             */
            data_time: string;
            /**
             * Freshness Label
             * @enum {string}
             */
            freshness_label: "real" | "delayed";
            /** Instrument */
            instrument: string;
            /** Interval */
            interval: string;
            /**
             * Predecessor Data Time
             * Format: date-time
             */
            predecessor_data_time: string;
            /** Predecessor Sequence */
            predecessor_sequence: number;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "real" | "delayed";
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Sequence */
            sequence: number;
            /**
             * Sequence Gap
             * @constant
             */
            sequence_gap: false;
            /** Source */
            source: string;
            venue: components["schemas"]["Venue"];
        };
        /**
         * Order
         * @description Replayable order; state fields must agree with the event history.
         */
        Order: {
            /** Broker Order Id */
            broker_order_id?: string | null;
            /** Client Order Id */
            client_order_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Events */
            events?: components["schemas"]["OrderEvent"][];
            /**
             * Filled Quantity
             * @default 0
             */
            filled_quantity: number;
            /** Idempotency Key */
            idempotency_key?: string | null;
            instrument: components["schemas"]["Instrument"];
            /** Limit Price */
            limit_price?: number | null;
            /** Order Id */
            order_id: string;
            order_type: components["schemas"]["OrderType"];
            /** Quantity */
            quantity: number;
            side: components["schemas"]["Side"];
            /** @default pending */
            status: components["schemas"]["OrderStatus"];
        };
        /**
         * OrderEvent
         * @description One append-only lifecycle record; state is derived from this history.
         *
         *     Fill events carry the venue's own deal id and fee when the venue
         *     reported them, so fills can be re-derived from the history for
         *     fill-level reconciliation (ADR-0006 decision 4).
         */
        OrderEvent: {
            /** Broker Fill Id */
            broker_fill_id?: string | null;
            event_type: components["schemas"]["OrderEventType"];
            /** Fee */
            fee?: number | null;
            /** Price */
            price?: number | null;
            /** Quantity */
            quantity?: number | null;
            /** Reason */
            reason?: string | null;
            /** Sequence */
            sequence: number;
            status: components["schemas"]["OrderStatus"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * OrderEventType
         * @enum {string}
         */
        OrderEventType: "accepted" | "rejected" | "fill" | "canceled";
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending" | "accepted" | "partially_filled" | "filled" | "canceled" | "rejected";
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "market" | "limit";
        /**
         * PaperProposal
         * @description Immutable forecast-to-paper intent; creation never places an order.
         */
        PaperProposal: {
            /** Artifact Id */
            artifact_id: string;
            /** Blockers */
            blockers?: string[];
            /** Config Digest */
            config_digest: string;
            /** Confirmation Token */
            confirmation_token: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Revision */
            dataset_revision: number;
            /**
             * Forecast Generated At
             * Format: date-time
             */
            forecast_generated_at: string;
            /** History Digest */
            history_digest: string;
            /** Id */
            id: string;
            instrument: components["schemas"]["InstrumentSnapshot"];
            /** Limit Price */
            limit_price?: number | null;
            /** Model Version */
            model_version: string;
            /** Order Id */
            order_id?: string | null;
            order_type: components["schemas"]["OrderType"];
            /** Quantity */
            quantity: number;
            /** Quote Provenance */
            quote_provenance?: ("real" | "demo-synthetic") | null;
            side: components["schemas"]["Side"];
            status: components["schemas"]["ProposalStatus"];
        };
        /** ProposalCapability */
        ProposalCapability: {
            /** Allowed */
            allowed: boolean;
            /** Blockers */
            blockers: string[];
            /** Proposals */
            proposals: components["schemas"]["PaperProposal"][];
        };
        /** ProposalConfirmBody */
        ProposalConfirmBody: {
            /** Confirmation Token */
            confirmation_token: string;
        };
        /**
         * ProposalConfirmation
         * @description Typed result of an explicit confirmation attempt.
         */
        ProposalConfirmation: {
            /** Blocker */
            blocker?: string | null;
            order?: components["schemas"]["Order"] | null;
            proposal: components["schemas"]["PaperProposal"];
            /** Quote Provenance */
            quote_provenance?: ("real" | "demo-synthetic") | null;
        };
        /** ProposalCreateBody */
        ProposalCreateBody: {
            /** Artifact Id */
            artifact_id: string;
            /** Limit Price */
            limit_price?: number | null;
            /** Quantity */
            quantity: number;
            side: components["schemas"]["Side"];
            /** Symbol */
            symbol: string;
            venue: components["schemas"]["Venue"];
        };
        /**
         * ProposalStatus
         * @description Append-only paper proposal lifecycle.
         * @enum {string}
         */
        ProposalStatus: "pending" | "blocked" | "confirmed" | "rejected";
        /**
         * Side
         * @enum {string}
         */
        Side: "buy" | "sell";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Venue
         * @enum {string}
         */
        Venue: "internal" | "moomoo" | "hyperliquid" | "polymarket" | "kalshi";
        /**
         * WorkspaceForecast
         * @description Forecast evidence needed by the workspace, without bulky OOS rows.
         */
        WorkspaceForecast: {
            /** Artifact Id */
            artifact_id: string;
            /** Benchmark Name */
            benchmark_name: string;
            /** Blockers */
            blockers: string[];
            /** Config Digest */
            config_digest: string;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Revision */
            dataset_revision: number;
            /** Eligible */
            eligible: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** History Digest */
            history_digest: string;
            /** Limitations */
            limitations: string[];
            /** Metrics */
            metrics: components["schemas"]["ForecastMetrics"][];
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Paths */
            paths: components["schemas"]["ForecastPath"][];
            /** Target */
            target: string;
            /** Test End */
            test_end?: string | null;
            /** Test Start */
            test_start?: string | null;
            /**
             * Train End
             * Format: date-time
             */
            train_end: string;
            /**
             * Train Start
             * Format: date-time
             */
            train_start: string;
            /** Validation End */
            validation_end?: string | null;
            /** Validation Start */
            validation_start?: string | null;
        };
        /**
         * WorkspaceLiveEvidence
         * @description One truthful latest quote view; absent data stays explicitly absent.
         */
        WorkspaceLiveEvidence: {
            /** Age Ms */
            age_ms?: number | null;
            /** Ask */
            ask?: number | null;
            /** Bid */
            bid?: number | null;
            /** Data Time */
            data_time?: string | null;
            /** Label */
            label?: string | null;
            /** Last */
            last?: number | null;
            /** Provenance */
            provenance?: string | null;
            /** Reason */
            reason?: string | null;
            /** Received At */
            received_at?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Sequence Gap */
            sequence_gap?: boolean | null;
            /** Source */
            source?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "degraded" | "unavailable";
        };
        /** WorkspacePosition */
        WorkspacePosition: {
            /** Average Cost */
            average_cost: number;
            /** Mark */
            mark?: number | null;
            /** Quantity */
            quantity: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl?: number | null;
        };
        /** WorkspaceRisk */
        WorkspaceRisk: {
            /** Cash */
            cash: number;
            /** Equity */
            equity: number;
            /** Global Kill Switch */
            global_kill_switch: boolean;
            /** Mark Available */
            mark_available: boolean;
            /** Max Notional */
            max_notional?: number | null;
            /** Max Order Quantity */
            max_order_quantity?: number | null;
            /** Max Position Quantity */
            max_position_quantity?: number | null;
            /** Starting Cash */
            starting_cash: number;
            /** Venue Kill Switch */
            venue_kill_switch: boolean;
        };
        /**
         * _KillSwitchBody
         * @description The JSON kill-switch flip the SPA shell calls. The form endpoint
         *     stays the RC1 contract; both flip the same account object and
         *     replace it in app.state and the page context, so the JSON surface,
         *     every page and the kernel gate agree (ADR-0011 decision 6).
         */
        _KillSwitchBody: {
            /**
             * Action
             * @enum {string}
             */
            action: "engage" | "disarm";
            /** Venue */
            venue?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    redirect__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    account_summary_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_account_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_enablement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_experiments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_forecasts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    api_instrument_history: {
        parameters: {
            query: {
                range: components["schemas"]["HistoryRange"];
                compare?: string[] | null;
            };
            header?: never;
            path: {
                venue: components["schemas"]["Venue"];
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_instrument_workspace: {
        parameters: {
            query: {
                range: components["schemas"]["HistoryRange"];
                compare?: string[] | null;
            };
            header?: never;
            path: {
                venue: components["schemas"]["Venue"];
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_kill_switch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_kill_switch_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_KillSwitchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_live_prediction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    api_live_price_trail: {
        parameters: {
            query: {
                /** @description Comma-separated instrument symbols */
                symbols: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_live_replay: {
        parameters: {
            query?: {
                /** @description ISO-8601 window start */
                start?: string | null;
                /** @description ISO-8601 window end */
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_live_replay_windows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_live_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_live_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_live_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_markets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    api_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_create_paper_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_confirm_paper_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalConfirmBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalConfirmation"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalConfirmation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_pnl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_positions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    api_promotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_risk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    redirect_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_enablement_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_forecasts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    redirect_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instrument_history_instruments__venue___symbol__history_get: {
        parameters: {
            query: {
                range: components["schemas"]["HistoryRange"];
                compare?: string[] | null;
            };
            header?: never;
            path: {
                venue: components["schemas"]["Venue"];
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instrument_workspace_instruments__venue___symbol__workspace_get: {
        parameters: {
            query: {
                range: components["schemas"]["HistoryRange"];
                compare?: string[] | null;
            };
            header?: never;
            path: {
                venue: components["schemas"]["Venue"];
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_switch_kill_switch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    kill_switch_post_kill_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_kill_switch_post_kill_switch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redirect_kill_switch_control_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    live_prediction_live_prediction_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    live_price_trail_live_price_trail_get: {
        parameters: {
            query: {
                /** @description Comma-separated instrument symbols */
                symbols: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_replay_live_replay_get: {
        parameters: {
            query?: {
                /** @description ISO-8601 window start */
                start?: string | null;
                /** @description ISO-8601 window end */
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_replay_windows_live_replay_windows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    live_state_live_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    live_status_live_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    live_stream_live_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    orders_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    order_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_paper_proposal_paper_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_paper_proposal_paper_proposals__proposal_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalConfirmBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalConfirmation"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalConfirmation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pnl_pnl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    redirect_portfolio_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_portfolio_pnl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    positions_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    redirect_promotions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redirect_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    watchlist_add_watchlist_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_watchlist_add_watchlist_add_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_remove_watchlist_remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_watchlist_remove_watchlist_remove_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
