"""Research and backtesting integration points."""

from quantmesh.research.baselines import (
    book_imbalance_weights,
    low_volatility_weights,
    run_baseline_report,
    run_walk_forward,
)
from quantmesh.research.experiments import (
    Experiment,
    ExperimentRegistry,
    experiment_id,
)
from quantmesh.research.features import (
    FEATURES,
    FeatureKind,
    FeatureRegistry,
    FeatureSet,
    FeatureSpec,
    compute_feature,
    compute_features,
    feature_id,
    featureset_id,
    frame_digest,
)
from quantmesh.research.models import (
    LinearModel,
    ModelRecord,
    ModelRegistry,
    ModelSpec,
    artifact_path,
    fit_model,
    model_id,
)
from quantmesh.research.pipelines import (
    PIPELINE_KINDS,
    GARCHPipeline,
    HMMPipeline,
    LightGBMPipeline,
    LogisticPipeline,
    PipelineUnavailableError,
    direction_labels,
    pipeline_digest,
    run_pipeline_report,
)
from quantmesh.research.reports import (
    MODEL_STRATEGIES,
    CostModel,
    ReportRegistry,
    StrategyReport,
    UniverseMember,
    WalkForwardSpec,
    WindowResult,
    artifact_paths,
    report_id,
)

__all__ = [
    "CostModel",
    "Experiment",
    "ExperimentRegistry",
    "FEATURES",
    "FeatureKind",
    "FeatureRegistry",
    "FeatureSet",
    "FeatureSpec",
    "GARCHPipeline",
    "HMMPipeline",
    "LightGBMPipeline",
    "LinearModel",
    "LogisticPipeline",
    "MODEL_STRATEGIES",
    "ModelRecord",
    "ModelRegistry",
    "ModelSpec",
    "PIPELINE_KINDS",
    "PipelineUnavailableError",
    "ReportRegistry",
    "StrategyReport",
    "UniverseMember",
    "WalkForwardSpec",
    "WindowResult",
    "artifact_path",
    "artifact_paths",
    "book_imbalance_weights",
    "compute_feature",
    "compute_features",
    "direction_labels",
    "experiment_id",
    "feature_id",
    "featureset_id",
    "fit_model",
    "frame_digest",
    "low_volatility_weights",
    "model_id",
    "pipeline_digest",
    "report_id",
    "run_baseline_report",
    "run_pipeline_report",
    "run_walk_forward",
]
