"""Walk-forward strategy reports: pinned setup, deterministic identity (issue #27).

A ``StrategyReport`` records everything that defines a baseline run —
dataset, manifest revision, code commit, strategy, interval, universe,
window spec, cost model — and nothing that results from it, so the same
setup always produces the same 16-hex ID (ADR-0005, mirroring
``experiment_id`` from issue #18). Results (metrics, per-window results)
and artifact paths (deterministic functions of the ID) ride along as
outputs.

``ReportRegistry`` persists reports as JSONL with the experiment-registry
discipline: atomic appends, fail-closed reads with line attribution,
duplicate IDs refused, and every recorded pin validated through the
lake's manifest gate. A report that exists is one whose data still
exists at the pinned revision, whose setup is recorded verbatim, and
whose artifacts can be regenerated byte-identical.
"""

import hashlib
import json
import math
import os
import subprocess
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from pydantic import (
    BaseModel,
    Field,
    ValidationError,
    field_validator,
    model_validator,
)

from quantmesh.data.lake import Dataset, Lake
from quantmesh.data.layout import validate_dataset_name
from quantmesh.domain.market_data import interval_to_timedelta
from quantmesh.domain.models import Venue
from quantmesh.settings import settings

REPORTS_FILE = "reports.jsonl"

ID_PATTERN = "^[0-9a-f]{16}$"
COMMIT_PATTERN = "^[0-9a-f]{7,64}$"

Parameter = str | int | float | bool | None

STRATEGIES = ("momentum", "mean_reversion", "risk_parity")

# Bars per trading day for annualization: 252 trading days, each of
# 24h/interval (a "1d" bar covers one trading day, "5m" covers 288).
_SECONDS_PER_DAY = 86400


class CostModel(BaseModel):
    """One cost model owned by QuantMesh, applied to every baseline (ADR-0005).

    The one-way rate is the sum of the three components over 10_000,
    charged on each unit of one-way turnover at a rebalance. Costs are
    decimal fractions; non-finite values are rejected at the boundary.
    """

    fee_bps: float = Field(ge=0)
    half_spread_bps: float = Field(ge=0)
    slippage_bps: float = Field(ge=0)

    @field_validator("fee_bps", "half_spread_bps", "slippage_bps")
    @classmethod
    def components_are_finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError(f"cost component must be finite, got {value}")
        return value

    def rate(self) -> float:
        """One-way cost per unit of turnover, as a decimal fraction."""
        return (self.fee_bps + self.half_spread_bps + self.slippage_bps) / 10_000.0


class WalkForwardSpec(BaseModel):
    """Count-based walk-forward windows over the observed bar grid (ADR-0005).

    ``train_bars`` must be at least 2 (a one-bar train cannot estimate
    returns or volatility) and ``step_bars`` at least ``test_bars``
    (evaluation segments never overlap, so the equity curve concatenates
    without double counting). Splitting is calendar-free: it operates on
    bar counts, so a pinned dataset pins the windows.
    """

    train_bars: int = Field(ge=2)
    test_bars: int = Field(ge=1)
    step_bars: int = Field(ge=1)

    @model_validator(mode="after")
    def segments_never_overlap(self) -> "WalkForwardSpec":
        if self.step_bars < self.test_bars:
            raise ValueError(
                f"step_bars ({self.step_bars}) must be >= test_bars ({self.test_bars}) "
                "so evaluation segments never overlap"
            )
        return self

    def test_starts(self, n_bars: int) -> list[int]:
        """Indices where each test segment begins, in a grid of ``n_bars``.

        A window at index ``j`` trains on bars ``[j - train_bars, j)``
        and evaluates on ``[j, j + test_bars)``. Fails closed when the
        grid cannot host even one window.
        """
        starts = []
        candidate = self.train_bars
        while candidate + self.test_bars <= n_bars:
            starts.append(candidate)
            candidate += self.step_bars
        if not starts:
            raise ValueError(
                f"grid of {n_bars} bars cannot host {self.model_dump()} "
                f"(need at least train_bars + test_bars = {self.train_bars + self.test_bars})"
            )
        return starts


class UniverseMember(BaseModel):
    """One symbol of the report's universe, pinned by venue and symbol."""

    venue: Venue
    symbol: str = Field(min_length=1)


class WindowResult(BaseModel):
    """One walk-forward evaluation segment's outcome (ADR-0005 units)."""

    index: int = Field(ge=0)
    train_end: datetime
    test_start: datetime
    test_end: datetime
    window_return: float
    turnover: float = Field(ge=0)
    cost: float = Field(ge=0)
    n_trades: int = Field(ge=0)

    @field_validator("window_return", "turnover", "cost")
    @classmethod
    def values_are_finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError(f"window value must be finite, got {value}")
        return value

    @model_validator(mode="after")
    def timestamps_are_aware(self) -> "WindowResult":
        for name in ("train_end", "test_start", "test_end"):
            if getattr(self, name).tzinfo is None:
                raise ValueError(f"{name} must be timezone-aware")
        return self


def report_id(
    *,
    dataset: str,
    revision: int,
    commit: str,
    strategy: str,
    interval: str,
    universe: list[UniverseMember],
    window_spec: WalkForwardSpec,
    costs: CostModel,
) -> str:
    """Deterministic identity of a report: setup only, never results.

    The universe hashes over its sorted member list, so member order
    does not change the identity (ADR-0005 decision 2).
    """
    members = sorted((member.venue.value, member.symbol) for member in universe)
    setup = {
        "dataset": dataset,
        "revision": revision,
        "commit": commit,
        "strategy": strategy,
        "interval": interval,
        "universe": members,
        "window_spec": window_spec.model_dump(),
        "costs": costs.model_dump(),
    }
    canonical = json.dumps(setup, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(f"baseline-report\0{canonical}".encode()).hexdigest()[:16]


class StrategyReport(BaseModel):
    """One recorded baseline run: pinned setup plus observed results."""

    id: str = Field(pattern=ID_PATTERN)
    dataset: str
    revision: int = Field(ge=1)
    commit: str = Field(pattern=COMMIT_PATTERN)
    strategy: str
    interval: str
    universe: list[UniverseMember]
    window_spec: WalkForwardSpec
    costs: CostModel
    created_at: datetime
    metrics: dict[str, Parameter] = Field(default_factory=dict)
    windows: list[WindowResult] = Field(default_factory=list)

    @field_validator("metrics")
    @classmethod
    def metrics_are_finite(cls, values: dict[str, Parameter]) -> dict[str, Parameter]:
        for name, value in values.items():
            if isinstance(value, float) and not math.isfinite(value):
                raise ValueError(f"metric {name!r} is not finite ({value})")
        return values

    @model_validator(mode="after")
    def report_is_consistent(self) -> "StrategyReport":
        validate_dataset_name(self.dataset)
        if self.strategy not in STRATEGIES:
            raise ValueError(f"unknown strategy {self.strategy!r} (expected {STRATEGIES})")
        interval_to_timedelta(self.interval)
        if self.created_at.tzinfo is None:
            raise ValueError("created_at must be timezone-aware")
        self.created_at = self.created_at.astimezone(UTC)
        expected = report_id(
            dataset=self.dataset,
            revision=self.revision,
            commit=self.commit,
            strategy=self.strategy,
            interval=self.interval,
            universe=self.universe,
            window_spec=self.window_spec,
            costs=self.costs,
        )
        if self.id != expected:
            raise ValueError(
                f"report id {self.id!r} does not match its pinned setup (expected {expected!r})"
            )
        return self


def artifact_paths(root: Path, report: StrategyReport) -> dict[str, Path]:
    """Deterministic artifact locations for a report (ADR-0005 decision 7)."""
    directory = root / report.id
    return {
        "report.json": directory / "report.json",
        "equity_curve.csv": directory / "equity_curve.csv",
        "trades.csv": directory / "trades.csv",
    }


class ReportRegistry:
    """Append-only store of strategy reports under one registry root."""

    def __init__(self, root: Path | None = None, lake_root: Path | None = None) -> None:
        self.root = root if root is not None else settings.reports_dir
        self.lake_root = lake_root if lake_root is not None else settings.lake_root

    def record(self, report: StrategyReport) -> StrategyReport:
        """Record a report; the pin is validated before anything is written.

        Refuses duplicate IDs — the same setup is the same report, and a
        rerun regenerates identical artifacts instead of recording again.
        """
        existing = self.all()
        if any(record.id == report.id for record in existing):
            raise ValueError(f"report {report.id!r} already recorded")
        self._require_pin(report)
        self._append(report, existing)
        return report

    def get(self, report_id_value: str) -> StrategyReport:
        for report in self.all():
            if report.id == report_id_value:
                return report
        raise ValueError(f"no report recorded with id {report_id_value!r}")

    def all(self) -> list[StrategyReport]:
        return self._read()

    def resolve(self, report_id_value: str) -> Dataset:
        """Re-open the report's dataset, pinned to its revision.

        The lake's manifest gate checks the bytes match the declaration;
        this additionally refuses when the manifest has moved past the
        pinned revision.
        """
        report = self.get(report_id_value)
        self._require_pin(report)
        return Lake(self.lake_root).dataset(report.dataset)

    def resolve_pin(self, dataset: str, revision: int) -> Dataset:
        """The dataset at a pinned revision, through the lake's manifest gate."""
        dataset_handle = Lake(self.lake_root).dataset(dataset)
        if dataset_handle.manifest.revision != revision:
            raise ValueError(
                f"dataset {dataset!r} is now revision {dataset_handle.manifest.revision}, "
                f"but the pin asks for revision {revision}"
            )
        return dataset_handle

    def _require_pin(self, report: StrategyReport) -> None:
        self.resolve_pin(report.dataset, report.revision)

    def _append(self, report: StrategyReport, existing: list[StrategyReport]) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        path = self.root / REPORTS_FILE
        descriptor, temp_name = tempfile.mkstemp(
            dir=self.root, prefix=f".{REPORTS_FILE}.", suffix=".tmp"
        )
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                for record in existing + [report]:
                    handle.write(record.model_dump_json())
                    handle.write("\n")
            os.replace(temp_name, path)
        finally:
            if os.path.exists(temp_name):
                os.unlink(temp_name)

    def _read(self) -> list[StrategyReport]:
        if not self.root.exists():
            return []
        if not self.root.is_dir():
            raise ValueError(f"report registry root {self.root} is not a directory")
        path = self.root / REPORTS_FILE
        if not path.exists():
            return []
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as error:
            raise ValueError(f"report registry {path} is unreadable") from error
        records = []
        seen: dict[str, int] = {}
        for line_number, line in enumerate(text.splitlines(), start=1):
            if not line.strip():
                continue
            try:
                record = StrategyReport.model_validate_json(line)
            except ValidationError as error:
                raise ValueError(
                    f"report registry {path} line {line_number} is invalid"
                ) from error
            if record.id in seen:
                raise ValueError(
                    f"report registry {path} lines {seen[record.id]} and "
                    f"{line_number} share a report id"
                )
            seen[record.id] = line_number
            records.append(record)
        return records


def current_commit() -> str:
    """HEAD of the git repository the registry runs in; else fail closed."""
    try:
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError) as error:
        raise ValueError("cannot resolve the code commit; pass commit explicitly") from error
    if not head:
        raise ValueError("cannot resolve the code commit; pass commit explicitly")
    return head
