"""Local AI research layer integration points (M8)."""

from quantmesh.ai.errors import (
    ModelConfigurationError,
    ModelError,
    ModelOutputError,
    ModelProtocolError,
    ModelUnavailableError,
    PipelineError,
    UnknownRoleError,
)
from quantmesh.ai.gateway import ModelGateway
from quantmesh.ai.roles import (
    CHARTERS,
    ROLE_ORDER,
    AnalystReport,
    Claim,
    CriticGateResult,
    CriticVerdict,
    FlaggedClaim,
    PortfolioReview,
    ResearchPipeline,
    ResearchResult,
    RiskFinding,
    RiskReview,
    RoleCharter,
    charter,
)
from quantmesh.ai.transport import (
    DEFAULT_CHAT_PATH,
    MODEL_API_KEY_ENV,
    HttpModelTransport,
    ModelTransport,
    ScriptedModelTransport,
)
from quantmesh.ai.wire import (
    ChatMessage,
    ModelRequest,
    ModelResponse,
    build_chat_body,
    parse_completion,
)

__all__ = [
    "AnalystReport",
    "CHARTERS",
    "ChatMessage",
    "Claim",
    "CriticGateResult",
    "CriticVerdict",
    "DEFAULT_CHAT_PATH",
    "FlaggedClaim",
    "HttpModelTransport",
    "MODEL_API_KEY_ENV",
    "ModelConfigurationError",
    "ModelError",
    "ModelGateway",
    "ModelOutputError",
    "ModelProtocolError",
    "ModelRequest",
    "ModelResponse",
    "ModelTransport",
    "ModelUnavailableError",
    "PipelineError",
    "PortfolioReview",
    "ROLE_ORDER",
    "ResearchPipeline",
    "ResearchResult",
    "RiskFinding",
    "RiskReview",
    "RoleCharter",
    "ScriptedModelTransport",
    "UnknownRoleError",
    "build_chat_body",
    "charter",
    "parse_completion",
]
